-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Employers"
(
    id integer NOT NULL,
    company_name character varying(100),
    phone character varying(15),
    website character varying(100),
    PRIMARY KEY (id)
);

CREATE TABLE public."Jobseekers"
(
    id integer NOT NULL,
    birth_date date,
    first_name character varying(20),
    last_name character varying(20),
    national_identity character varying(11),
    PRIMARY KEY (id)
);

CREATE TABLE public."SystemPersonnel"
(
    id integer NOT NULL,
    first_name character varying(20),
    last_name character varying(20),
    PRIMARY KEY (id)
);

CREATE TABLE public."Users"
(
    "Id" integer NOT NULL,
    "Mail" character varying(50),
    "Password" character varying(50),
    PRIMARY KEY ("Id")
);

CREATE TABLE public.jobpositions
(
    id integer NOT NULL,
    job_name character varying(20),
    PRIMARY KEY (id)
);

ALTER TABLE public."Employers"
    ADD FOREIGN KEY (id)
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."Jobseekers"
    ADD FOREIGN KEY (id)
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."SystemPersonnel"
    ADD FOREIGN KEY (id)
    REFERENCES public."Users" ("Id")
    NOT VALID;

END;